### ISSUE TITLE
关于pytorch版本

### ISSUE THREAD

**Issue by dawei03896** [hzwer/ECCV2022-RIFE#244]
您好，我使用pytorch1.6以及更高的版本训练，loss比使用pytorch1.5训练，大很多，会不会用问题？

**Comment by hzwer** [comment]
我好像没遇到过这个问题

**Comment by zhangzhuo12** [comment]
想问一下您使用这个网络后，怎样才能对一系列图片来进行测试，而不是只能对指定的两张来测试

**Comment by hzwer** [comment]
@zhangzhuo12 您可以查看 https://github.com/hzwer/arXiv2021-RIFE/tree/main/benchmark 中的各个测试文件

**Comment by hzwer** [comment]
loss 大的情况，可能是由于初始化差异导致的，一般稍微调小点 learning rate 即可。
因为我这边用过很多版本的 torch，没看到明显差异，故先关闭这个 issue
