### ISSUE TITLE
Issues when interpolating images or videos shot from different view angles 

### ISSUE THREAD

**Issue by compressionist** [hzwer/ECCV2022-RIFE#254]
Hi all,

I have the following question.

I'm trying to interpolate between two images or a video where each frame is taken from a different view angle (for example, spheric videos). Is it possible to do this with the help of RIFE?

If I run **inference_img.py** in the default mode, the interpolated **img1.png** is received with high visual artifacts (attached). 

In short, what should I do to interpolate such images? For example, I can change my source to add more view angles, or should I look for different algorithms, or maybe I need to retrain RIFE for spheric videos or images or change a parameter in **inference_img.py** or **inference_video.py**? 

I appreciate any help you can provide.

![img0](https://user-images.githubusercontent.com/12200629/165805926-22ab058c-18db-4e23-a499-0c5c6bbb6bb1.png)
![img1](https://user-images.githubusercontent.com/12200629/165806411-9af517ac-44ec-4907-a9c2-e1d530fb7144.png)
![img2](https://user-images.githubusercontent.com/12200629/165806463-425a9a81-69cd-416e-91d8-5c43112b89e3.png)

**Comment by hzwer** [comment]
Hi, view interpolation is not a situation we currently cover, but I have done some work on it.
I have two suggestions:
1. Use a SLAM-related dataset to finetune the model, such as TartanAir.
2. Add some image translation augmentation during training to force the model to understand camera motion.

**Comment by compressionist** [comment]
Hi @hzwer, Thanks a lot for the tip! 

Do you think interpolation with RIFE can give us a better result than if we first run colmap and then run one of the view synthesis methods (for example, using nerf_pl or instant-ngp)? I already tried to make a 3D model from our images using instant-ngp, it works very fast, but we are not satisfied with the visual result. 

As for your work in the field of view interpolation, is it possible to see at least partial results of your research somewhere?

**Comment by hzwer** [comment]
What I envision is to try a nerf-like method to get coarse results first, and then use a RIFE-like method to transfer textures, since RIFE doesn't directly model view changes.
I think IBRNet (https://ibrnet.github.io/) is a good solution right now. Our method is not yet public, sorry.
