### ISSUE TITLE
who knows the parameters meaning?

### ISSUE THREAD

**Issue by Ferrarilover** [hzwer/ECCV2022-RIFE#308]
who knows the parameters meaning? or where find it?

**Comment by hzwer** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/10103856/232666247-7c61153d-7614-44a3-b98f-e50dc2dfd02e.png">

If you prefer GUI and end-to-end usage, you may check https://github.com/megvii-research/ECCV2022-RIFE#software

**Comment by Ferrarilover** [comment]
这是来自QQ邮箱自动回复邮件。
 
您好，我已经收到您的邮件。阅读后尽快给您回复。

**Comment by Ferrarilover** [comment]
> <img alt="image" width="1116" src="https://user-images.githubusercontent.com/10103856/232666247-7c61153d-7614-44a3-b98f-e50dc2dfd02e.png">
> 
> If you prefer GUI and end-to-end usage, you may check https://github.com/megvii-research/ECCV2022-RIFE#software

我看过这个，我现在碰到的问题是用里面的模型推理提升帧率后发现视频里面的人看起来动作变慢了，变得不那么像正常动作。但是视频时长并未改变。

**Comment by hzwer** [comment]
如果时长没改变可能是对的 插帧视频看起来是会有变慢的感觉

**Comment by Ferrarilover** [comment]
好像不是这样，看到有些地方用了这个算法动作并没有变慢，至少人眼感觉不出来



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 18, 2023 21:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [megvii-research/ECCV2022-RIFE] who knows the parameters meaning?(Issue #308)




 
如果时长没改变可能是对的 插帧视频看起来是会有变慢的感觉

**Comment by hzwer** [comment]
针对具体case可能需要逐帧查看结果 从这个描述我不是很能理解具体发生了什么
