### ISSUE TITLE
question about encode

### ISSUE THREAD

**Issue by MichalTurek** [hzwer/ECCV2022-RIFE#346]
Hi, could you please describe what exactly is done and what's the output of encode in IFNet.forward()
```
 f0 = self.encode(img0[:, :3])
  f1 = self.encode(img1[:, :3])
```
It outputs tensor of size (1,8,width,height) but what exactly this tensor represents?

**Comment by hzwer** [comment]
My detailed ideas can be seen in https://arxiv.org/abs/2310.17294.
Warping features is better than only warping images, refer to [Context-aware synthesis for video frame interpolation](https://www.google.com.hk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjSqM-KiZ2DAxUO8WEKHa0hDFwQgAMoAHoECAUQAw&url=https%3A%2F%2Fscholar.google.com%2Fscholar_url%3Furl%3Dhttp%3A%2F%2Fopenaccess.thecvf.com%2Fcontent_cvpr_2018%2Fpapers%2FNiklaus_Context-Aware_Synthesis_for_CVPR_2018_paper.pdf%26hl%3Dzh-CN%26sa%3DX%26ei%3DNl-CZbrpI9eS6rQPgK-FiAE%26scisig%3DAFWwaeZRimTdAZtGdlsS9CK2-8tw%26oi%3Dscholarr&usg=AOvVaw0ryZJCDoUt3bEDkifevXlZ&opi=89978449)

**Comment by MichalTurek** [comment]
okay, thank you. Another thing, is there any paper which further explain how mask is estimated? I am talking about mask which is used for forward and backward warped images merge into final output?
