### ISSUE TITLE
视频如何做8倍插帧

### ISSUE THREAD

**Issue by ustczhouyu** [hzwer/ECCV2022-RIFE#364]
请问视频如何做8倍插帧，是通过exp参数控制吗？我执行python3 inference_video.py --exp=8 --video=video.mp4不是想要的结果，此外，scale参数的作用是什么？ @hzwer @HeylonNHP @ko1N @zsc

**Comment by hzwer** [comment]
exp = 3 
如果分辨率很大就设置 scale=0.5，不然就设置 1.0
