### ISSUE TITLE
几个不同版本模型的关系和区别是什么

### ISSUE THREAD

**Issue by guijuzhejiang** [hzwer/ECCV2022-RIFE#365]
非常感谢开源的工作，我下载了readme中提到的三个模型：RIFE_trained_model_v3.6，RIFE_trained_v6，RIFE_m_train_log。其中的RIFE_m_train_log运行错误，可能是因为没有对应的RIFE_HDv3.py代码。
问题1：这三个模型的版本号没看懂，对应的模型效果强弱顺序是什么？
问题2：如何运行RIFE_m_train_log模型？
问题3：和Practical-RIFE中提供的模型v4.×××的关系是什么样的？是否是v4.18是目前效果最好的模型？
提前感谢！

**Comment by hzwer** [comment]
你好，RIFEm 和 RIFEv6 好像是论文发布的模型
如果你只是为了插帧应用，可以直接用 v4.18，是面向应用发的模型

**Comment by guijuzhejiang** [comment]
感谢回复，使用最新版v4.18，over
