### ISSUE TITLE
模型部署

### ISSUE THREAD

**Issue by yeluohuazhifou** [hzwer/ECCV2022-RIFE#376]
你好，请教一下，当前模型转成tflite后，在移动端测试发现挺慢的，分析发现是因为warp模块里的grid_sample函数，转成tflite实现后，不能在tflite gpu运行，只能跑在cpu上，导致速度很慢，请问您那边有遇到过类似问题吗。我现在的策略是训练的时候只是用单尺度，然后导出模型只到处flow出来，使用后处理做warp，这样速度会快很多，但是单尺度效果上会差一些，请问能给一些改进思路吗

**Comment by hzwer** [comment]
你好，我研究过，单尺度效果就是会差很多
也许在图片金字塔上做再整合会好一点，完全去掉网络内部的 grid_sample 总是会损伤性能

**Comment by yeluohuazhifou** [comment]
> 你好，我研究过，单尺度效果就是会差很多，完全去掉网络内部的 grid_sample 总是会损伤性能 也许在图片金字塔上做整合会好一点

是滴，目前局限于部署平台的限制，做图片金字塔性能风险也很大；因为我现在相当于只用模型输出的光流，然后后处理remap得到插帧图像，在想用纯光流算法会不会好一点，但是测试了几个最新的纯光流算法，在插帧任务中并没有特别好的表现

**Comment by yeluohuazhifou** [comment]
请教下，因为考虑到部署要求，我把interpolate下采样用conv2d卷积下采样替换，interpolate上采样用ConvTranspose2d上采样替换，PixelShuffle上采样替换成了ConvTranspose2d上采样，但是不清楚这些替换对性能影响大不大，您那边有做过相关的消融实验吗

**Comment by hzwer** [comment]
上下采样用哪个应该区别不大的

**Comment by Shirifo** [comment]
@yeluohuazhifou 您好，我也在做类似的实验，想只用论文中提到的算光流的模型，想请问您是怎么修改训练代码的呢
