### ISSUE TITLE
训练RIFEm

### ISSUE THREAD

**Issue by ZXMMD** [hzwer/ECCV2022-RIFE#377]
作者您好，当我尝试训练RIFEm时，我注意到 ：
https://github.com/hzwer/ECCV2022-RIFE/blob/638322e8bfe6daca4439f7b56503fef4b090d34f/train.py#L67

请问我是否应该对下列代码进行修改，增加一个timestep参数？
https://github.com/hzwer/ECCV2022-RIFE/blob/638322e8bfe6daca4439f7b56503fef4b090d34f/model/RIFE.py#L67-L95

**Comment by hzwer** [comment]
是的
